name: Deploy to GitHub Releases
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Container (arm32)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.arm32
          tags: dashd_builder:arm32
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Container (arm64)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.arm64
          tags: dashd_builder:arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build DashD (arm32)
        run: docker run --rm --volume ${{github.workspace}}:/dashd/app dashd_builder:arm32

      - name: Build DashD (arm64)
        run: docker run --rm --volume ${{github.workspace}}:/dashd/app dashd_builder:arm64

      - name: Deploy to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/*
